/// Flutter icons MyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData profile_fill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reels = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reels_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_fill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_fill = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_fill = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf35f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
